In [4]:
import numpy as np
list1=[10,20,30,40,50]
array1=np.array(list1)
print(array1)

[10 20 30 40 50]


In [6]:
import numpy as np
list1=[[10,20,30],[40,50,60],[70,80,90]]
array1=np.array(list1)
print(array1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [64]:
import numpy as np
array1=np.arange (1,8)
print(array1)

[1 2 3 4 5 6 7]


In [68]:
import numpy as np
array1=np.arange(11,17).reshape((2,3))
print(array1)

[[11 12 13]
 [14 15 16]]


In [74]:
import numpy as np
array1=np.arange(11,17).reshape((3,2))
print(array1)

[[11 12]
 [13 14]
 [15 16]]


In [76]:
import numpy as np
array1=np.arange(11,20).reshape((3,3))
print(array1)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [78]:
import numpy as np
array1=np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [80]:
import numpy as np
array1=np.zeros((4,2))
print(array1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [84]:
import numpy as np
array1=np.ones((2,4))
print(array1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
import numpy as np
array1=np.ones(4)
print(array1)

[1. 1. 1. 1.]


In [38]:
import numpy as np
array1=np.ones((4,2))
print(array1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [48]:
import numpy as np
list1=[10,20,30,40,50]
array1=np.array(list1)
print(array1)
array1.ndim

[10 20 30 40 50]


1

In [46]:
import numpy as np
list1=[[10,20,30,],[40,50,60],[70,80,90]]
array1=np.array(list1)
print(array1)
array1.ndim

[[10 20 30]
 [40 50 60]
 [70 80 90]]


2

In [122]:
import numpy as np
array3=np.array([[[1,2,3],[4,5,6]],
       [[7,8,9],[10,11,12]]])
print(array3)
array3.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

In [96]:
import numpy as np
list1=[10,20,30,40,50]
array1=np.array(list1)
print(array1)
array1.shape

[10 20 30 40 50]


(5,)

In [94]:
import numpy as np
list1=[[10,20,30],[40,50,60],[70,80,90]]
array1=np.array(list1)
print(array1)
array1.shape

[[10 20 30]
 [40 50 60]
 [70 80 90]]


(3, 3)

In [120]:
import numpy as np
array3=np.array([[[1, 2, 3],[4, 5, 6]],
                [[7,8,9],[10,11,12]]])
print(array3)
array3.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [124]:
import numpy as np
list1=[10,20,30,40,50]
array1=np.array(list1)
print(array1)
array1.size

[10 20 30 40 50]


5

In [126]:
import numpy as np
list1=[[10,20,30],[40,50,60],[70,80,90]]
array1=np.array(list1)
print(array1)
array1.size

[[10 20 30]
 [40 50 60]
 [70 80 90]]


9

In [128]:
import numpy as np
array3=np.array([[[1, 2, 3],[4, 5, 6]],
                [[7,8,9],[10,11,12]]])
print(array3)
array1.size

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


9

In [130]:
import numpy as np
list1=[10,20,30,40,50]
array1=np.array(list1)
print(array1)
array1.dtype

[10 20 30 40 50]


dtype('int32')

In [132]:
import numpy as np
list1=[[10,20,30],[40,50,60],[70,80,90]]
array1=np.array(list1)
print(array1)
array1.size
array1.dtype

[[10 20 30]
 [40 50 60]
 [70 80 90]]


dtype('int32')

In [134]:
import numpy as np
array3=np.array([[[1, 2, 3],[4, 5, 6]],
                [[7,8,9],[10,11,12]]])
print(array3)
array1.dtype

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


dtype('int32')

In [136]:
import numpy as np
list1=[10,20,30,40,50]
array1=np.array(list1)
print(array1)
array1.itemsize

[10 20 30 40 50]


4

In [138]:
import numpy as np
list1=[[10,20,30],[40,50,60],[70,80,90]]
array1=np.array(list1)
print(array1)
array1.itemsize

[[10 20 30]
 [40 50 60]
 [70 80 90]]


4

In [140]:
import numpy as np
array3=np.array([[[1, 2, 3],[4, 5, 6]],
                [[7,8,9],[10,11,12]]])
print(array3)
array1.itemsize

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


4