In [5]:
import numpy as np


In [9]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [13]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [15]:
type(my_list)

list

In [45]:
arr=np.array(my_list)

In [47]:
arr

array([0, 1, 2, 3, 4, 5])

In [49]:
type(arr)

numpy.ndarray

In [51]:
type(my_list)

list

In [55]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [63]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
np.arange(3.0)

array([0., 1., 2.])

In [67]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [71]:
np.arange(20,10)

array([], dtype=int32)

In [73]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [75]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [77]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [79]:
np.arange(30,20)

array([], dtype=int32)

In [83]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [85]:
np.arange(10,10)

array([], dtype=int32)

In [87]:
np.arange()

TypeError: arange() requires stop to be specified.

In [89]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [91]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [93]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [95]:
np.zeros(3)

array([0., 0., 0.])

In [97]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [99]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [101]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [103]:
zero=np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [105]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [107]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [109]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [111]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [113]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [115]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [117]:
print(np.zeros(n,dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [119]:
n

(6, 7)

In [121]:
n1

(6, 8)

In [123]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [125]:
np.ones(3)

array([1., 1., 1.])

In [127]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [131]:
np.ones(4)

array([1., 1., 1., 1.])

In [133]:
n

(6, 7)

In [135]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [137]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [139]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [141]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [143]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [145]:
np.ones(2)

array([1., 1.])

In [147]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [149]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [151]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [153]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [155]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [157]:
range(5)

range(0, 5)

In [159]:
r=range(5)
r

range(0, 5)

In [161]:
for i in r:
    print(i)

0
1
2
3
4


In [163]:
list(range(5))

[0, 1, 2, 3, 4]

In [165]:
range(1,10)

range(1, 10)

In [169]:
list(range(1,10,3))

[1, 4, 7]

In [171]:
y=list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [173]:
rand(3,2)

NameError: name 'rand' is not defined

In [175]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [215]:
np.random.rand(5)

array([0.54452658, 0.33996169, 0.15257854, 0.52507332, 0.44827006])

In [217]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [219]:
np.random.rand(2,4)

array([[0.89400835, 0.73323566, 0.37072323, 0.42598688],
       [0.03010568, 0.63315608, 0.64460374, 0.92911187]])

In [221]:
np.random.randint(2,4)

3

In [231]:
np.random.randint(2,20)

14

In [233]:
np.random.randint(0,1)

0

In [235]:
np.random.randint(1,6,4)

array([2, 1, 1, 1])

In [237]:
np.random.rand(3)

array([0.5576677 , 0.25139596, 0.03180715])

In [239]:
np.random.randint(1)

0

In [241]:
np.random.randint(30,20,10)

ValueError: low >= high

In [243]:
np.random.randint(-30,20,10)

array([ 13, -14, -18, -24,  -6,   7, -29,  16,  18, -23])

In [245]:
np.random.randint(20,30,10)

array([25, 23, 27, 20, 23, 20, 24, 25, 20, 22])

In [247]:
np.random.randint(5,9)

5

In [249]:
np.random.randint(10,21,3)

array([12, 12, 10])

In [251]:
np.random.randint(1,12,10)

array([10,  6,  6,  5,  7,  6,  6,  1,  6,  8])

In [253]:
np.random.randint(10,40,(10,10))

array([[12, 16, 15, 33, 12, 14, 33, 27, 25, 32],
       [27, 38, 38, 24, 32, 30, 18, 22, 26, 38],
       [17, 34, 10, 28, 18, 35, 21, 20, 24, 17],
       [38, 36, 38, 25, 17, 29, 20, 20, 12, 12],
       [11, 30, 33, 32, 18, 32, 15, 18, 21, 22],
       [30, 27, 29, 34, 29, 20, 12, 25, 28, 38],
       [11, 26, 25, 33, 37, 30, 37, 16, 32, 33],
       [28, 21, 38, 22, 13, 39, 21, 23, 22, 17],
       [18, 12, 34, 14, 21, 16, 36, 38, 30, 26],
       [26, 28, 25, 20, 17, 19, 20, 35, 27, 19]])

In [255]:
np.random.randint(1,100,(12,12))

array([[67, 74, 46, 92, 35, 55, 68, 50, 72, 11, 88, 79],
       [25, 54, 96, 20, 29, 98, 56, 29, 36, 87, 19, 91],
       [ 6, 50, 10, 59, 76, 31, 48, 76, 83, 20,  6, 11],
       [57, 10, 68, 75, 49, 56, 90, 37, 33, 76, 83,  6],
       [79, 26, 46, 45, 23, 19,  7, 28, 67, 80, 81, 34],
       [22, 20,  9,  7, 52, 25, 45, 70, 57, 11, 93,  8],
       [44, 47, 16, 63,  4, 74,  9,  4,  3, 16, 29, 12],
       [35, 24, 27, 64, 19, 30, 96, 97, 13,  1, 77, 42],
       [82, 89,  3, 55, 65, 55, 26, 53, 57, 30, 81, 73],
       [23, 93, 19, 96, 38, 77, 54, 11,  8,  9, 96,  4],
       [93, 50, 28, 46, 85, 62, 81, 20,  2, 52, 95, 39],
       [57, 74, 52, 96, 12,  3, 28, 93, 29, 56, 51, 46]])

In [257]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [259]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [265]:
b=np.random.randint(10,20,(5,4))
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [267]:
type(b)

numpy.ndarray

In [269]:
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [271]:
b[:]

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [273]:
b[1:3]

array([[10, 18, 14, 13],
       [18, 15, 18, 15]])

In [275]:
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [279]:
b[1,3]

13

In [281]:
b[1,-1]

13

In [283]:
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [285]:
b[2:3]

array([[18, 15, 18, 15]])

In [287]:
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [289]:
b[0:-2]

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15]])

In [291]:
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [293]:
b[0,2]

12

In [295]:
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [297]:
b[-5,-3]

16

In [299]:
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [301]:
b[-4,2]

14

In [303]:
np.random.randint(10,20,(4,4))

array([[16, 16, 10, 12],
       [17, 16, 16, 19],
       [10, 19, 18, 15],
       [10, 14, 17, 11]])

In [305]:
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [307]:
b[-4,-2]

14

In [309]:
b

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [311]:
b[-4:2]

array([[10, 18, 14, 13]])

In [313]:
b[:]

array([[15, 16, 12, 18],
       [10, 18, 14, 13],
       [18, 15, 18, 15],
       [13, 16, 16, 17],
       [12, 15, 11, 10]])

In [315]:
a=np.random.randint(10,20,10)
a

array([11, 11, 10, 11, 13, 14, 10, 14, 12, 14])

In [317]:
id(a)

2073778616624

In [319]:
arr

array([0, 1, 2, 3, 4, 5])

In [323]:
arr2=np.random.randint(0,100,(10,10))

In [325]:
arr2

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [60, 61, 97, 32, 59, 14, 11, 91, 68, 73]])

In [327]:
arr

array([0, 1, 2, 3, 4, 5])

In [329]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [331]:
arr

array([0, 1, 2, 3, 4, 5])

In [333]:
arr[:4]

array([0, 1, 2, 3])

In [335]:
arr2[:]

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [60, 61, 97, 32, 59, 14, 11, 91, 68, 73]])

In [337]:
arr2[0:5]

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81]])

In [339]:
arr2

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [60, 61, 97, 32, 59, 14, 11, 91, 68, 73]])

In [341]:
arr2[1,4]

2

In [343]:
arr2

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [60, 61, 97, 32, 59, 14, 11, 91, 68, 73]])

In [345]:
arr2[-5,5]

52

In [347]:
arr2[-5,-5]

52

In [349]:
arr2


array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [60, 61, 97, 32, 59, 14, 11, 91, 68, 73]])

In [351]:
arr2[-1,-2]

68

In [355]:
arr2

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [60, 61, 97, 32, 59, 14, 11, 91, 68, 73]])

In [359]:
arr2[::-1]

array([[60, 61, 97, 32, 59, 14, 11, 91, 68, 73],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [23, 55,  8, 56, 70, 97, 15, 83, 65, 52]])

In [361]:
arr2

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [60, 61, 97, 32, 59, 14, 11, 91, 68, 73]])

In [363]:
arr2[::-2]

array([[60, 61, 97, 32, 59, 14, 11, 91, 68, 73],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25]])

In [365]:
arr2

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [60, 61, 97, 32, 59, 14, 11, 91, 68, 73]])

In [367]:
arr2[::-3]

array([[60, 61, 97, 32, 59, 14, 11, 91, 68, 73],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [23, 55,  8, 56, 70, 97, 15, 83, 65, 52]])

In [369]:
arr2

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33],
       [51, 30, 53, 64, 95, 13, 88,  3, 78, 17],
       [ 8, 94, 10, 67, 63, 84, 75, 12,  4, 55],
       [60, 61, 97, 32, 59, 14, 11, 91, 68, 73]])

In [371]:
arr2[:-3]

array([[23, 55,  8, 56, 70, 97, 15, 83, 65, 52],
       [73, 50, 64, 63,  2, 98, 31, 29, 49, 25],
       [40, 69, 32,  6, 71, 57, 81, 17, 46, 24],
       [88, 99, 59,  4, 93, 34, 30, 23, 20, 77],
       [55,  2, 59, 70,  4, 48, 50, 76, 94, 81],
       [ 0, 22, 61, 70, 16, 52, 85, 80, 98, 76],
       [88, 72, 10, 39, 85, 69,  3, 34, 73, 33]])

In [373]:
arr

array([0, 1, 2, 3, 4, 5])

In [375]:
arr.max()

5

In [377]:
arr.min()

0

In [379]:
arr

array([0, 1, 2, 3, 4, 5])

In [381]:
arr.mean()

2.5

In [383]:
arr

array([0, 1, 2, 3, 4, 5])

In [385]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [387]:
from numpy import*
a=array([1,2,3,4,9])
median(a)

3.0

In [389]:
arr

array([0, 1, 2, 3, 4, 5])

In [391]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [393]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [395]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [397]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [399]:
arr

array([0, 1, 2, 3, 4, 5])

In [401]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [403]:
arr

array([0, 1, 2, 3, 4, 5])

In [407]:
arr.reshape(2,3,order='c')

array([[0, 1, 2],
       [3, 4, 5]])

In [409]:
arr.reshape(2,3,order='f')

array([[0, 2, 4],
       [1, 3, 5]])

In [411]:
arr.reshape(2,3,order='a')

array([[0, 1, 2],
       [3, 4, 5]])

In [413]:
arr

array([0, 1, 2, 3, 4, 5])

In [415]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [417]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [419]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [421]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [423]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [425]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [427]:
arr

array([0, 1, 2, 3, 4, 5])

In [429]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [431]:
mat=np.arange(0,100).reshape(10,10)

In [433]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [435]:
row=4
col=5

In [439]:
row

4

In [442]:
col

5

In [444]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [446]:
mat[row,col]

45

In [448]:
mat[4,5]

45

In [450]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [452]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [454]:
col=6

In [456]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [458]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [460]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [462]:
#with slices
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [464]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [466]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [468]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [470]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [472]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [474]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [476]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [478]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [480]:
row

4

In [482]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [486]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [488]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [490]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [492]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [494]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [496]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [498]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [500]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [502]:
row

4

In [504]:
col

6

In [506]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [508]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [510]:
mat[1,4]

14

In [512]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [514]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [516]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [518]:
mat[3:3]

array([], shape=(0, 10), dtype=int32)

In [520]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [522]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [524]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [526]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [528]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [530]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [532]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [534]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [536]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [538]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [540]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [542]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [544]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [546]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [548]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [550]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [552]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [554]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [556]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [558]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [560]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [562]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [564]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [566]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [568]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [570]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [572]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [574]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [576]:
mat[0,1]

1

In [578]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [580]:
mat[1,6]

16

In [582]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [584]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [586]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [588]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [592]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [594]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [596]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [598]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [600]:
mat[3,5]

35

In [602]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [604]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [606]:
mat[1:2,2:4]

array([[12, 13]])

In [608]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [610]:
mat[2:3,2:3]

array([[22]])

In [612]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [614]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [616]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [618]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [620]:
mat[2:3,4:5]

array([[24]])

In [622]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [624]:
id(mat)

2073778735024

In [626]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [628]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [630]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [632]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [634]:
mat[mat==50]

array([50])

In [636]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [638]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [644]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [646]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [648]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [650]:
a2=mat[mat<50]
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [652]:
a3=mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [654]:
a4=mat[mat==50]
a4

array([50])

In [682]:

import random
def generate_otp(length=4):
    """generate a numeric otp of a specified length."""
    digits='012345'
    otp =''.join(random.choice(digits)for_in range(length))
    return otp
     otp_length=4
    otp=generate_otp(otp_length)
    print(f"your otp is:{otp}")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (589764133.py, line 5)

In [666]:
def wish():
    print('good even')
    wish()

def wish():
    print('good even')
    wish()

def wish():
    print('good even')
    wish()

In [668]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [672]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x000001E2D6D9F540>


In [674]:
x=[1,2,3]
y=x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
