# import numpy as np

In [ ]:
Array a: [1 2 3]

In [19]:
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [9]:
b=np.arange(0,10,2)
print("Array b:",b)

Array b: [0 2 4 6 8]


In [11]:
c=np.linspace(0,1,5)
print("Array c:",c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [13]:
d=np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
e=np.ones((3,2))
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
f=np.eye(4)
print("identity matrix f:\n",f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
#Reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))
print("reshaped array:",reshaped)

reshaped array: [[1 2 3]]


In [23]:
#flatten an array
f1=np.array([[1,2],[3,4]])
flattened=np.ravel(f1)
print("flattened array:",flattened)

flattened array: [1 2 3 4]


In [16]:
#transpose an array
import numpy as np
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1) 
print("transposed array:\n",transposed)

transposed array:
 [[1 3]
 [2 4]]


In [18]:
#stack arrays vertically
import numpy as np
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])
print("stacked arrays:\n",stacked)

stacked arrays:
 [[1 2]
 [3 4]]


In [20]:
#add two arrays
import numpy as np
g=np.array([1,2,3,4])
added=np.add(g,2)
print("added 2 to g:",added)

added 2 to g: [3 4 5 6]


In [22]:
#square each element 
import numpy as np
squared=np.power(g,2) 
print("squared g:",squared)

squared g: [ 1  4  9 16]


In [24]:
import numpy as np
sqrt_val=np.sqrt(g)
print("square root of g:",sqrt_val)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [30]:
a=np.array([1,2,3])
a1=np.array([1,2,3])
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [32]:
import numpy as np
a3=np.array([1,2,3])
dot_product=np.dot(a1,a)
print("dot product of a1 and a:",dot_product)

dot product of a1 and a: 14


In [40]:
#mean of array
import numpy as np
s=np.array([1,2,3,4])
mean=np.mean(s)
print("mean of s:",mean)

mean of s: 2.5


In [42]:
#standard deviatin of an array
import numpy as np
std_dev=np.std(s)
print("standard deviation of s:",std_dev)

standard deviation of s: 1.118033988749895


In [44]:
#minimize element of an array
import numpy as np
minimum=np.min(s)
print("min of s:",minimum)

min of s: 1


In [46]:
#maximum element of an array
import numpy as np
maximum=np.max(s)
print("max of s:",maximum)

max of s: 4


In [50]:
#create a matrix
import numpy as np
matrix=np.array([[1,2],[3,4]])
print("matrix:",matrix)

matrix: [[1 2]
 [3 4]]


In [52]:
#determinant of a matrix
import numpy as np
determinant=np.linalg.det(matrix)
print("determinant of matrix:",determinant)

determinant of matrix: -2.0000000000000004


In [54]:
#inverse of a matrix
import numpy as np
inverse=np.linalg.inv(matrix)
print("inverse of matrix:\n",inverse)

inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
